/**
 * FAAN FINAL - 3 AI + Telegram Webhook /start /sinyal
 */
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"*","Access-Control-Allow-Headers":"*","Content-Type":"application/json"};
const GROQ_KEY=Deno.env.get("GROQ_KEY")||"";const OPENROUTER_KEY=Deno.env.get("OPENROUTER_KEY")||"";const META_KEY=Deno.env.get("META_KEY")||GROQ_KEY;const TELEGRAM_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")||"";const TELEGRAM_CHAT=Deno.env.get("TELEGRAM_CHAT_ID")||"";
async function sendTelegram(text:string,chatId?:string){const target=chatId||TELEGRAM_CHAT;if(!TELEGRAM_TOKEN||!target)return{ok:false};const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:target,text,parse_mode:"Markdown"})});return await r.json();}
function calcRSI(p:number[],per=7){if(p.length<per+1)return 50;let g=0,l=0;for(let i=p.length-per;i<p.length;i++){if(i<=0)continue;const d=p[i]-p[i-1];if(d>=0)g+=d;else l-=d;}if(l===0)return 100;const rs=g/(l||1);return 100-100/(1+rs);}
function calcEMA(p:number[],per:number){const k=2/(per+1);let e:number[]=[];let sma=p.slice(0,per).reduce((a,b)=>a+b,0)/per;e.push(sma);for(let i=per;i<p.length;i++)e.push(p[i]*k+e[e.length-1]*(1-k));return e;}
async function callGroq(prompt:string){const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${GROQ_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.3-70b-versatile",messages:[{role:"user",content:prompt}],temperature:0.2})});const j=await r.json();return j.choices?.[0]?.message?.content||"";}
async function callDeepSeek(prompt:string){const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${OPENROUTER_KEY}`,"Content-Type":"application/json","HTTP-Referer":"https://fannmarket.web.app","X-Title":"FAAN"},body:JSON.stringify({model:"deepseek/deepseek-r1:free",messages:[{role:"user",content:prompt}],temperature:0.2})});const j=await r.json();return j.choices?.[0]?.message?.content||"";}
async function callMeta(prompt:string){const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${META_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama3-70b-8192",messages:[{role:"user",content:prompt}],temperature:0.3})});const j=await r.json();return j.choices?.[0]?.message?.content||"";}
async function getSignal(id="bitcoin",pair="BTCUSDT"){const[chart,detail]=await Promise.all([fetch(`https://api.coingecko.com/api/v3/coins/${id}/market_chart?vs_currency=usd&days=1`).then(r=>r.json()),fetch(`https://api.coingecko.com/api/v3/coins/${id}`).then(r=>r.json())]);const prices:number[]=chart.prices.map((p:any)=>p[1]);const volumes:number[]=chart.total_volumes.map((v:any)=>v[1]);const rsi7=calcRSI(prices,7);const rsi14=calcRSI(prices,14);const ema9=calcEMA(prices,9).pop()||0;const ema21=calcEMA(prices,21).pop()||0;const low=Math.min(...prices.slice(-20));const high=Math.max(...prices.slice(-20));const lastVol=volumes[volumes.length-1]||0;const avgVol=volumes.slice(-20).reduce((a,b)=>a+b,0)/20;const volSpike=avgVol>0?(lastVol/avgVol):1;const groqPrompt=`SCANNER Groq ${pair} Harga ${detail.market_data?.current_price?.usd} RSI7 ${rsi7.toFixed(2)} EMA9 ${ema9.toFixed(2)} EMA21 ${ema21.toFixed(2)} Support ${low} Resist ${high} Vol ${volSpike.toFixed(1)}x`;let g="";g=await callGroq(groqPrompt);let d=await callDeepSeek(`STRATEGIST DeepSeek: ${g} RSI7 ${rsi7.toFixed(2)} RSI14 ${rsi14.toFixed(2)}`);let m=await callMeta(`COMMUNICATOR: ${d||g} Jadi JSON final + telegram_alert`);let final=m||d||g;const jm=final.match(/\{[\s\S]*\}/);return jm?jm[0]:final;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{headers:CORS});const url=new URL(req.url);if(url.pathname==="/"){return new Response(JSON.stringify({ok:true,stack:"FAAN 3 AI + Telegram",providers:{groq:!!GROQ_KEY,openrouter:!!OPENROUTER_KEY,meta:!!META_KEY,telegram:!!TELEGRAM_TOKEN},webhook:"/webhook"}),{headers:CORS});}if(url.pathname==="/webhook"){try{const b=await req.json();const msg=b.message||b.edited_message;const chatId=msg?.chat?.id?.toString();const text=msg?.text?.trim()||"";const username=msg?.from?.username||"trader";if(!chatId)return new Response("ok",{headers:CORS});if(text.startsWith("/start")){await sendTelegram(`🚀 *FAAN SIGNAL BOT AKTIF*\n\nHalo @${username}!\n\n/start - menu\n/sinyal - BTCUSDT\n/sinyal ETH - ETHUSDT\n/status - cek AI`,chatId);}else if(text.startsWith("/sinyal")){const parts=text.split(" ");const pair=(parts[1]||"BTCUSDT").toUpperCase();const id=pair.includes("ETH")?"ethereum":"bitcoin";await sendTelegram(`⏳ Analisa ${pair} 1m...`,chatId);try{const fj=await getSignal(id,pair);const p=JSON.parse(fj);if(p.sinyal?.status==="WAIT"){await sendTelegram(`⏸️ *${pair} WAIT* - ${p.sinyal?.alasan_3_poin?.[0]||"Ranging"}`,chatId);}else{await sendTelegram(`🚀 *FAAN ALERT* ${pair} ${p.sinyal?.status} @ ${p.manajemen_risiko?.entry}\nSL ${p.manajemen_risiko?.stop_loss} TP ${p.manajemen_risiko?.take_profit_1}`,chatId);}}catch(e:any){await sendTelegram(`❌ ${e.message}`,chatId);}}return new Response(JSON.stringify({ok:true}),{headers:CORS});}catch(e){return new Response(JSON.stringify({ok:false}),{headers:CORS});}}if(url.pathname==="/signal"){const id=url.searchParams.get("id")||"bitcoin";const pair=url.searchParams.get("pair")||"BTCUSDT";try{const fj=await getSignal(id,pair);try{const p=JSON.parse(fj);if(p.sinyal?.status&&p.sinyal.status!=="WAIT"){await sendTelegram(`🚀 *FAAN SCALP ALERT* ${pair} ${p.sinyal?.status} @ ${p.manajemen_risiko?.entry}`);}}catch{}return new Response(fj,{headers:CORS});}catch(e:any){return new Response(JSON.stringify({error:e.message}),{status:500,headers:CORS});}}return new Response(JSON.stringify({error:"Not found"}),{status:404,headers:CORS});});
